# -*- coding: utf-8 -*-
"""Copy of Final_Mindx 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swIjJfZUreyvsun7KZUM-qTRa82qFsDh
"""

#import lib
#import thư viện
import pandas as pd
import numpy as np
import matplotlib as plt
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import dates
import datetime
print('Completed import lib')

#Import File
df =  pd.read_csv('/content/marketplace_data_2019.csv')
df.info()

#Checking null Values
df.isnull().sum()

df.head(5)

#Unpivot dataframe 
df_unpivot = pd.wide_to_long(df,
                             stubnames =['clicks', 'cost','bookings','booking_rev'],  #select columns
                             i = ['date','ttt_group'], #
                             j = 'Advertiser', 
                             sep ='_', 
                             suffix ='\w+')
print(df_unpivot.head())

#Transforming MultiIndex to Columns
df = df_unpivot.reset_index()
print(df.head())
df.info()

#Save file 
df.to_csv('Final_mindx.csv')